### PR TITLE
F kotur

### PR DESCRIPTION
**Pull request by filipkotur**

### CODE REVIEW

**Comment by jsribar** [comment]
Popraviti build error.

**Comment by filipkotur** [comment]
Probao sam ali nemogu nikako da mi prepozna fleetgrid u formmain mogu jedino obrisat.
--------------------------------------------
On Tue, 4/9/19, Julijan Šribar <notifications@github.com> wrote:

 Subject: Re: [vsite-oom/Battleship] F kotur (#57)
 To: "vsite-oom/Battleship" <Battleship@noreply.github.com>
 Cc: "filip kotur" <koturfilip@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, April 9, 2019, 7:10 AM
 
 Popraviti build error.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jsribar** [comment]
Poštovanje,
Imate nekoliko pogrešaka u kodu:

   1.
   https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FleetGrid.cs#L86
-
   nedostaje zagrada u pozivu konstruktora
   2.
   https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FleetGrid.cs#L77
   - nedostaje jedan argument u pozivu metode DrawLine
   3. Metoda InitializeComponent (koju Visual Studio automatski generira
   prilikom stvaranja forme)
   https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FormMain.cs#L20
   (uključujući i deklaraciju tipke button1) je na neku foru završila u krivoj
   datoteci (umjesto u FormMain.Designer.cs ona je u FormMain.cs). Očito ste
   išli raditi nešto na svoju ruku i pogrešno. Popravite to:
      1. Taj dio koda vratite u FormMainDesigner.cs iza linije
      https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FormMain.Designer.cs#L23
      2. Izbrišite deklaraciju tipke buttonGenerate
      https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FormMain.Designer.cs#L27
      3. Ispred deklaracije tipke button1 umetnite naredbu
      #endregion
      4. Izbrišite naredbu koja baca iznimku (
      https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FleetGrid.cs#L63
      )

Nakon toga biste trebali moći buildati projekt i dodati FleetGrid kontrolu
na glavnu formu.

Molim Vas da ubuduće pažljivije pratite nastavu, a ne na pola uha da Vam se
ne događaju ovakve gluposti.

Srdačan pozdrav,

Julijan Šribar

**Comment by jsribar** [comment]
Zaboravio sam još jednu stvar: treba promijeniti namespace u liniji
https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FormMain.cs#L11

**Comment by filipkotur** [comment]
Napravio sam sve ali i dalje nemam fleetgrid.
    On Wednesday, April 10, 2019, 11:18:13 AM GMT+2, Julijan Šribar <notifications@github.com> wrote:  
 
 Zaboravio sam još jednu stvar: treba promijeniti namespace u liniji
https://github.com/vsite-oom/Battleship/blob/2a66350bd1b1d99982ccb81159d39e3450861a31/FleetDisplay/FormMain.cs#L11

**Comment by jsribar** [comment]
Promijenite fleetGrid u fleetGrid1
<https://github.com/vsite-oom/Battleship/blob/3ec03373ff97a7d3f0858aae206f2783b5e44e57/FleetDisplay/FormMain.cs#L35>

**Comment by filipkotur** [comment]
Evo gotov sam puno hvala profesore.
    On Wednesday, April 10, 2019, 1:41:40 PM GMT+2, Julijan Šribar <notifications@github.com> wrote:  
 
 Promijenite fleetGrid u fleetGrid1
<https://github.com/vsite-oom/Battleship/blob/3ec03373ff97a7d3f0858aae206f2783b5e44e57/FleetDisplay/FormMain.cs#L35>

**Pull request closed without merging**
